//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDnsConfig) DeepCopyInto(out *ClusterDnsConfig) {
	*out = *in
	if in.SearchDomains != nil {
		in, out := &in.SearchDomains, &out.SearchDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDnsConfig.
func (in *ClusterDnsConfig) DeepCopy() *ClusterDnsConfig {
	if in == nil {
		return nil
	}
	out := new(ClusterDnsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterInfo) DeepCopyInto(out *ClusterInfo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterInfo.
func (in *ClusterInfo) DeepCopy() *ClusterInfo {
	if in == nil {
		return nil
	}
	out := new(ClusterInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterInfo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterInfoList) DeepCopyInto(out *ClusterInfoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterInfoList.
func (in *ClusterInfoList) DeepCopy() *ClusterInfoList {
	if in == nil {
		return nil
	}
	out := new(ClusterInfoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterInfoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterInfoSpec) DeepCopyInto(out *ClusterInfoSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterInfoSpec.
func (in *ClusterInfoSpec) DeepCopy() *ClusterInfoSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterInfoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterInfoStatus) DeepCopyInto(out *ClusterInfoStatus) {
	*out = *in
	in.ClusterDnsConfig.DeepCopyInto(&out.ClusterDnsConfig)
	out.ClusterResources = in.ClusterResources
	if in.NodeInfo != nil {
		in, out := &in.NodeInfo, &out.NodeInfo
		*out = make([]NodeInfo, len(*in))
		copy(*out, *in)
	}
	if in.RouterLBAddresses != nil {
		in, out := &in.RouterLBAddresses, &out.RouterLBAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ApiServerAddresses != nil {
		in, out := &in.ApiServerAddresses, &out.ApiServerAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IdentityProviders != nil {
		in, out := &in.IdentityProviders, &out.IdentityProviders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StorageProvisioners != nil {
		in, out := &in.StorageProvisioners, &out.StorageProvisioners
		*out = make([]StorageProvisioner, len(*in))
		copy(*out, *in)
	}
	if in.MutatingWebhooks != nil {
		in, out := &in.MutatingWebhooks, &out.MutatingWebhooks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ValidatingWebhooks != nil {
		in, out := &in.ValidatingWebhooks, &out.ValidatingWebhooks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Segments != nil {
		in, out := &in.Segments, &out.Segments
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterInfoStatus.
func (in *ClusterInfoStatus) DeepCopy() *ClusterInfoStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterInfoStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterResources) DeepCopyInto(out *ClusterResources) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterResources.
func (in *ClusterResources) DeepCopy() *ClusterResources {
	if in == nil {
		return nil
	}
	out := new(ClusterResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeInfo) DeepCopyInto(out *NodeInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeInfo.
func (in *NodeInfo) DeepCopy() *NodeInfo {
	if in == nil {
		return nil
	}
	out := new(NodeInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageProvisioner) DeepCopyInto(out *StorageProvisioner) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageProvisioner.
func (in *StorageProvisioner) DeepCopy() *StorageProvisioner {
	if in == nil {
		return nil
	}
	out := new(StorageProvisioner)
	in.DeepCopyInto(out)
	return out
}
