apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "axiom-operator.fullname" . }}-clusterinfo-admin-role
  labels:
  {{- include "axiom-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - axiom.dana.io
  resources:
  - clusterinfoes
  verbs:
  - '*'
- apiGroups:
  - axiom.dana.io
  resources:
  - clusterinfoes/status
  verbs:
  - get
